name: Build Android APK
on:
  push:
    paths:
      - 'app-settings.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create App and Build
        run: |
          cordova create myApp com.bittu.app "AppMaker"
          cd myApp
          cordova platform add android
          # यहाँ फाइल से URL उठाकर ऐप में सेट किया जा रहा है
          USER_URL=$(jq -r '.web_url' ../app-settings.json)
          sed -i "s|src=\"index.html\"|src=\"$USER_URL\"|" config.xml
          cordova build android --debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Generated-APK
          path: myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
          
