name: Build Android APK
on:
  push:
    paths:
      - 'app-settings.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create App and Build
        run: |
          # नया ऐप फोल्डर बनाना
          cordova create myApp com.bittu.app "AppMaker"
          cd myApp
          cordova platform add android@10.1.2
          
          # JSON से URL और Name निकालकर config में डालना
          APP_NAME=$(jq -r '.app_name' ../app-settings.json)
          WEB_URL=$(jq -r '.web_url' ../app-settings.json)
          
          sed -i "s|src=\"index.html\"|src=\"$WEB_URL\"|" config.xml
          sed -i "s|<name>AppMaker</name>|<name>$APP_NAME</name>|" config.xml
          
          # APK बनाना
          cordova build android --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Generated-APK
          path: myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
          
