name: Build Android APK
on:
  push:
    paths:
      - 'app-settings.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Tools
        run: |
          npm install -g cordova
          sudo apt-get install -y jq

      - name: Build Process
        run: |
          cordova create myApp com.bittu.app "App"
          cd myApp
          cordova platform add android@10.1.2
          
          # डेटा को सुरक्षित तरीके से निकालना
          NAME=$(jq -r '.app_name' ../app-settings.json | tr -d '\r\n')
          URL=$(jq -r '.web_url' ../app-settings.json | tr -d '\r\n')
          
          sed -i "s|<name>App</name>|<name>$NAME</name>|" config.xml
          sed -i "s|src=\"index.html\"|src=\"$URL\"|" config.xml
          
          chmod +x platforms/android/gradlew
          cordova build android --debug

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: My-APK
          path: myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
          
